services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 6379
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: ["redis-server"]  # Start Redis without requiring a password
  api:
    build: .
    container_name: certs365_dynamic
    restart: unless-stopped
    image: certs365_dynamic  # Use the pre-built image
    network_mode: bridge
    env_file:
      - .env
    ports:
      - 8001:8001
    environment:
      NODE_ENV: dev
      REDIS_HOST: redis  # Hostname of the Redis container
      REDIS_PORT: 6379    # Redis port
      REDIS_URL: redis://redis:6379  # Connection URL to Redis
    links:
      - redis

  # ghostscript:
  #   image: ubuntu:20.04
  #   container_name: ghostscript
  #   restart: unless-stopped
  #   network_mode: bridge
  #   environment:
  #     DEBIAN_FRONTEND: noninteractive
  #   command: >
  #     bash -c "apt-get update && 
  #               apt-get install -y ghostscript && 
  #               apt-get clean && 
  #               rm -rf /var/lib/apt/lists/* && 
  #               tail -f /dev/null"  # Keeps the container running

  # graphicsmagick:
  #   image: ubuntu:20.04
  #   container_name: graphicsmagick
  #   restart: unless-stopped
  #   network_mode: bridge
  #   environment:
  #     DEBIAN_FRONTEND: noninteractive
  #   command: >
  #     bash -c "apt-get update && 
  #               apt-get install -y graphicsmagick && 
  #               apt-get clean && 
  #               rm -rf /var/lib/apt/lists/* && 
  #               tail -f /dev/null"  # Keeps the container running